"""Fable 5 orchestrator: synthesizes one grounded research memo per company.

Pipeline: load real data → run the three specialist agents → one Fable 5
synthesis call whose findings each cite the specialist agent and carry its
attribution verbatim → code-side traceability verification → render the memo
to markdown with code-owned limitations and source lists.

The orchestrator may organise and weigh specialist outputs; it may not add
facts. Any finding whose attribution cannot be located in the cited
specialist's output is recorded as a traceability warning — visible in the
memo and to the Task 4 judge.
"""

from __future__ import annotations

import re
from datetime import UTC, datetime
from pathlib import Path
from typing import ClassVar, Literal

from pydantic import BaseModel, ConfigDict

from agents.base_agent import BaseAgent
from agents.comparison_agent import ComparisonAgent, ComparisonResult
from agents.cost_tracker import CostTracker
from agents.data_access import (
    load_company_year,
    load_filing_text,
    load_model_score,
)
from agents.extraction_agent import ExtractionAgent, ExtractionResult
from agents.signal_agent import MODEL_NATURE, SignalAgent, SignalResult
from core.logging import get_logger
from ingestion.sinks.snowflake_writer import ConnectionLike, open_connection

logger = get_logger(__name__)

MEMO_DIR = Path(__file__).parent.parent / "docs" / "sample_memos"

#: Code-owned limitations — present in every memo, never LLM-generated.
LIMITATIONS = (
    MODEL_NATURE,
    "Universe: current S&P 500 excluding Financials; training data carries "
    "survivorship bias that tilts the base rate positive.",
    "All inputs are information available at the 10-K filing date only; "
    "nothing after the filing date is reflected.",
    "Filing-language features cover ~56% of historical company-years; "
    "qualitative text analysis depends on best-effort section parsing.",
    "This memo is generated by an LLM pipeline from the sources listed below. "
    "Verify against the cited filings before relying on any claim.",
)


class MemoFinding(BaseModel):
    """One synthesized finding, citing its specialist agent and attribution."""

    finding: str
    source_agent: Literal["extraction", "comparison", "signal"]
    source_attribution: str


class MemoOutput(BaseModel):
    """What the orchestrator model returns."""

    summary: str
    findings: list[MemoFinding]
    confidence: Literal["low", "moderate", "high"]
    confidence_rationale: str


class ResearchMemo(BaseModel):
    """Full memo: model output wrapped in a code-supplied envelope."""

    model_config = ConfigDict(frozen=True)

    ticker: str
    fiscal_year: int
    generated_at: str
    summary: str
    findings: list[MemoFinding]
    confidence: str
    confidence_rationale: str
    limitations: tuple[str, ...]
    sources: list[str]
    traceability_warnings: list[str]
    extraction: ExtractionResult
    comparison: ComparisonResult
    signal: SignalResult


_SYSTEM_PROMPT = """\
You are the orchestrator of EDGAR-X, a financial research system. You receive \
the structured JSON outputs of three specialist agents that analysed REAL SEC \
and model data for one company-fiscal-year:
- extraction: attributed qualitative claims from the 10-K (with verbatim quotes)
- comparison: attributed year-over-year filing changes (with per-year evidence)
- signal: the XGBoost ranked-screen score interpreted against named ratios

Synthesize ONE coherent research memo.

Hard rules:
1. Every finding MUST derive from the specialist outputs. You may organise, \
weigh, and connect them; you may NOT add facts, numbers, or outside knowledge.
2. Each finding's source_agent names the specialist it came from, and \
source_attribution COPIES the specific evidence from that output verbatim — \
the source_quote, the per-year evidence, or the metric name with its value. \
Do not write new attribution text.
3. Respect every data_gap and caveat the specialists declared; reflect \
material ones in your confidence rationale.
4. The model score is a ranked-screen signal, not a prediction; never imply \
otherwise.
5. confidence is your honest overall assessment: high only if the specialist \
outputs are consistent, well-grounded, and gap-free; lower it for gaps, \
grounding warnings, or internal tension.
6. summary: 3-5 sentences a portfolio analyst could read standalone.
7. 6-10 findings, ordered by importance.
"""


class OrchestratorAgent(BaseAgent[MemoOutput]):
    """The Fable 5 synthesis call."""

    agent_name: ClassVar[str] = "orchestrator"
    max_output_tokens: ClassVar[int] = 8000
    output_schema: ClassVar[type[BaseModel]] = MemoOutput
    system_prompt: ClassVar[str] = _SYSTEM_PROMPT


def _normalise(text: str) -> str:
    """Lowercase and collapse whitespace for containment checks."""
    return re.sub(r"\s+", " ", text.lower()).strip()


def verify_traceability(
    findings: list[MemoFinding],
    *,
    extraction: ExtractionResult,
    comparison: ComparisonResult,
    signal: SignalResult,
) -> list[str]:
    """Check every finding's attribution exists in the cited specialist output.

    The attribution must appear (normalised substring) inside the JSON of the
    specialist output it cites. An attribution that cannot be located means
    the orchestrator paraphrased or invented evidence — flagged, not hidden.

    Args:
        findings: The orchestrator's findings.
        extraction: The extraction agent's real output.
        comparison: The comparison agent's real output.
        signal: The signal agent's real output.

    Returns:
        One warning per untraceable finding.
    """
    corpus = {
        "extraction": _normalise(extraction.model_dump_json()),
        "comparison": _normalise(comparison.model_dump_json()),
        "signal": _normalise(signal.model_dump_json()),
    }
    warnings: list[str] = []
    for finding in findings:
        attribution = _normalise(finding.source_attribution)
        # Allow minor truncation: check the first 60 normalised chars.
        probe = attribution[:60]
        if not probe or probe not in corpus[finding.source_agent]:
            warnings.append(
                f"finding cites {finding.source_agent} but its attribution was not "
                f"found in that agent's output: {finding.finding!r} "
                f"(attribution: {finding.source_attribution[:120]!r})"
            )
    if warnings:
        logger.warning("memo_traceability_warnings", count=len(warnings))
    return warnings


def generate_memo(
    ticker: str,
    fiscal_year: int,
    *,
    client: object | None = None,
    tracker: CostTracker | None = None,
    connection: ConnectionLike | None = None,
) -> ResearchMemo:
    """Generate one grounded research memo for a company-fiscal-year.

    Runs the three specialists and the orchestrator under one shared cost
    tracker (the spend cap applies to the whole memo), verifies traceability,
    and persists the memo to ``docs/sample_memos/{ticker}.md``.

    Args:
        ticker: Company ticker (non-Financial, in the loaded universe).
        fiscal_year: Fiscal year N to analyse.
        client: Optional injected Anthropic client (tests).
        tracker: Optional shared cost tracker.
        connection: Optional injected Snowflake connection.

    Returns:
        The full memo.

    Raises:
        ValueError: If the company-year has no data at all.
    """
    tracker = tracker or CostTracker()
    owns_connection = connection is None
    conn = connection or open_connection()
    try:
        current_features = load_company_year(ticker, fiscal_year, connection=conn)
        prior_features = load_company_year(ticker, fiscal_year - 1, connection=conn)
        current_filing = load_filing_text(ticker, fiscal_year, connection=conn)
        prior_filing = load_filing_text(ticker, fiscal_year - 1, connection=conn)
        score = load_model_score(ticker, fiscal_year, connection=conn)
    finally:
        if owns_connection:
            conn.close()

    if current_features is None or current_filing is None or score is None:
        raise ValueError(
            f"insufficient real data for {ticker} FY{fiscal_year}: "
            f"features={current_features is not None}, "
            f"filing={current_filing is not None}, score={score is not None}"
        )

    kwargs: dict[str, object] = {"tracker": tracker}
    if client is not None:
        kwargs["client"] = client
    extraction = ExtractionAgent(**kwargs).run(current_filing)  # type: ignore[arg-type]
    comparison = ComparisonAgent(**kwargs).run(  # type: ignore[arg-type]
        current_filing=current_filing,
        prior_filing=prior_filing,
        current_features=current_features,
        prior_features=prior_features,
    )
    signal = SignalAgent(**kwargs).run(score=score, features=current_features)  # type: ignore[arg-type]

    orchestrator = OrchestratorAgent(**kwargs)  # type: ignore[arg-type]
    output = orchestrator.run_prompt(
        ticker=ticker,
        user_content=(
            f"Company: {ticker}, fiscal year {fiscal_year}.\n\n"
            f"[EXTRACTION AGENT OUTPUT]\n{extraction.model_dump_json(indent=1)}\n\n"
            f"[COMPARISON AGENT OUTPUT]\n{comparison.model_dump_json(indent=1)}\n\n"
            f"[SIGNAL AGENT OUTPUT]\n{signal.model_dump_json(indent=1)}\n\n"
            f"Write the memo."
        ),
    )
    warnings = verify_traceability(
        output.findings, extraction=extraction, comparison=comparison, signal=signal
    )
    sources = sorted(set(extraction.sources + comparison.sources + signal.sources))
    memo = ResearchMemo(
        ticker=ticker.upper(),
        fiscal_year=fiscal_year,
        generated_at=datetime.now(UTC).isoformat(timespec="seconds"),
        summary=output.summary,
        findings=output.findings,
        confidence=output.confidence,
        confidence_rationale=output.confidence_rationale,
        limitations=LIMITATIONS,
        sources=sources,
        traceability_warnings=warnings,
        extraction=extraction,
        comparison=comparison,
        signal=signal,
    )
    path = MEMO_DIR / f"{memo.ticker}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_memo(memo))
    # Full structured memo persisted alongside for audit / judging.
    path.with_suffix(".json").write_text(memo.model_dump_json(indent=2))
    logger.info(
        "memo_generated",
        ticker=memo.ticker,
        findings=len(memo.findings),
        warnings=len(warnings),
        cost_usd=round(tracker.session_total_usd, 4),
    )
    return memo


def render_memo(memo: ResearchMemo) -> str:
    """Render the memo as auditable markdown.

    Args:
        memo: The full memo.

    Returns:
        Markdown with inline attribution on every claim.
    """
    lines = [
        f"# {memo.ticker} — FY{memo.fiscal_year} research memo",
        "",
        f"*Generated {memo.generated_at} by EDGAR-X (Claude Fable 5 pipeline). "
        f"Confidence: **{memo.confidence}**.*",
        "",
        "## Summary",
        "",
        memo.summary,
        "",
        f"**Model signal**: XGBoost ranked-screen score "
        f"**{memo.signal.xgboost_score:.4f}** for FY{memo.fiscal_year}. "
        f"{MODEL_NATURE}",
        "",
        "## Key findings",
        "",
    ]
    for index, finding in enumerate(memo.findings, start=1):
        lines += [
            f"{index}. {finding.finding}",
            f"   - *source: {finding.source_agent} agent — "
            f"“{finding.source_attribution}”*",
        ]
    lines += ["", f"**Confidence rationale**: {memo.confidence_rationale}", ""]

    if memo.traceability_warnings:
        lines += ["## ⚠ Traceability warnings", ""]
        lines += [f"- {warning}" for warning in memo.traceability_warnings]
        lines += [""]

    lines += ["## Year-over-year filing changes (comparison agent)", ""]
    if memo.comparison.changes:
        for change in memo.comparison.changes:
            current = change.current_year_evidence or "(absent this year)"
            prior = change.prior_year_evidence or "(absent prior year)"
            lines += [
                f"- **{change.change_type}** ({change.source_section}): {change.change}",
                f"  - FY{memo.comparison.current_fiscal_year}: “{current}”",
                f"  - FY{memo.comparison.prior_fiscal_year}: “{prior}”",
            ]
    else:
        lines += ["- none reported"]
    deltas = [d for d in memo.comparison.feature_deltas if d.delta not in (None, 0)]
    if deltas:
        lines += ["", "Numeric language-feature deltas (computed by dbt, not the LLM):", ""]
        lines += [
            f"- {d.feature}: {d.prior_value} → {d.current_value} (Δ {d.delta})"
            for d in deltas
        ]

    lines += ["", "## Filing claims (extraction agent)", ""]
    for claim in memo.extraction.claims:
        lines += [
            f"- [{claim.category} | {claim.source_section}] {claim.claim}",
            f"  - quote: “{claim.source_quote}”",
        ]

    lines += ["", "## Model-signal statements (signal agent)", ""]
    for statement in memo.signal.statements:
        lines += [
            f"- {statement.statement} "
            f"(*{statement.source_metric} = {statement.metric_value}*)"
        ]
    if memo.signal.grounding_warnings:
        lines += ["", "Grounding warnings (code-verified):", ""]
        lines += [f"- {w}" for w in memo.signal.grounding_warnings]

    gaps = memo.extraction.data_gaps + memo.comparison.data_gaps + memo.signal.caveats
    if gaps:
        lines += ["", "## Declared data gaps and caveats", ""]
        lines += [f"- {gap}" for gap in gaps]

    lines += ["", "## Limitations", ""]
    lines += [f"- {limitation}" for limitation in memo.limitations]
    lines += ["", "## Sources", ""]
    lines += [f"- {source}" for source in memo.sources]
    lines += [""]
    return "\n".join(lines)
